name: generators
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^4.0.0
  source_gen: ^4.0.2
  collection: any
  flutter_inappwebview_internal_annotations: ^1.2.0
    # path: ../flutter_inappwebview_internal_annotations

dev_dependencies:
  build_runner: ^2.10.2
  build_test: ^3.5.2
  test: ^1.25.8